import{redirect}from"next/navigation";import{BadgeCheck,Building2,FileText,ImageUp,MapPin}from"lucide-react";import{createClient}from"@/lib/supabase/server";import{updatePartnerProfile,uploadPartnerLogo}from"./actions";
type Props={searchParams:Promise<{success?:string;error?:string}>};
export const metadata={title:"Mitt BoLiv Partner"};
export default async function PartnerBackOffice({searchParams}:Props){const params=await searchParams;const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)redirect("/logga-in");const{data:member}=await supabase.from("partner_members").select("organization_id").eq("user_id",user.id).limit(1).single();if(!member)redirect("/");
 const[{data:org},{data:contracts},{data:placements}]=await Promise.all([supabase.from("partner_organizations").select("*").eq("id",member.organization_id).single(),supabase.from("partner_contracts").select("id,status,fortnox_invoice_number,due_at,paid_at,total_price_ex_vat").eq("organization_id",member.organization_id).order("created_at",{ascending:false}),supabase.from("partner_placements").select("id,status,municipalities(name),service_categories(name)").eq("organization_id",member.organization_id)]);
 if(!org)redirect("/");const logoUrl=org.logo_path?supabase.storage.from("partner-assets").getPublicUrl(org.logo_path).data.publicUrl:null;
 return <main className="dashboard partner-portal"><div className="dashboard-heading"><div><span className="kicker">Mitt BoLiv Partner</span><h1>{org.name}</h1><p>Hantera företagssidan, marknader och avtal.</p></div><span className={`partner-state ${org.profile_published?"active":"pending"}`}>{org.profile_published?"Publicerad":"Inväntar betalning"}</span></div>
 {params.success&&<div className="form-message success">{params.success}</div>}{params.error&&<div className="form-message error">{params.error}</div>}
 <div className="dashboard-stats"><div><MapPin/><span><strong>{placements?.length??0}</strong><small>Köpta marknader</small></span></div><div><BadgeCheck/><span><strong>{placements?.filter((p:any)=>p.status==="active").length??0}</strong><small>Aktiva platser</small></span></div><div><FileText/><span><strong>{contracts?.[0]?.fortnox_invoice_number??"–"}</strong><small>Senaste faktura</small></span></div></div>
 <section className="partner-portal-grid"><div className="partner-admin-section"><h2>Företagssida</h2><form action={updatePartnerProfile} className="property-form"><label>Företagsnamn<input name="name" defaultValue={org.name} required/></label><label>Presentation<textarea name="description" rows={6} defaultValue={org.description??""}/></label><div className="form-columns"><label>Publik e-post<input name="publicEmail" type="email" defaultValue={org.public_email??""}/></label><label>Telefon<input name="phone" defaultValue={org.phone??""}/></label></div><label>Webbplats<input name="websiteUrl" type="url" defaultValue={org.website_url??""}/></label><label>Adress<input name="address" defaultValue={org.address??""}/></label><div className="form-columns"><label>Postnummer<input name="postalCode" defaultValue={org.postal_code??""}/></label><label>Ort<input name="city" defaultValue={org.city??""}/></label></div><label>Öppettider<input name="openingHours" defaultValue={org.opening_hours??""}/></label><button className="button" type="submit">Spara företagssidan</button></form></div>
 <aside><div className="partner-admin-section logo-panel"><h2>Logotyp</h2>{logoUrl?<img src={logoUrl} alt={org.name}/>:<Building2/>}<form action={uploadPartnerLogo} className="property-form"><label><ImageUp/>Ladda upp logotyp<input name="logo" type="file" accept=".jpg,.jpeg,.png,.webp,.svg" required/></label><button className="button button-small">Spara logotyp</button></form></div>
 <div className="partner-admin-section"><h2>Marknader</h2>{placements?.map((p:any)=><div className="portal-market" key={p.id}><span><strong>{p.service_categories?.name}</strong><small>{p.municipalities?.name}</small></span><b>{p.status==="active"?"Aktiv":"Såld – inväntar betalning"}</b></div>)}</div>
 <div className="partner-admin-section"><h2>Avtal och faktura</h2>{contracts?.map(c=><div className="portal-contract" key={c.id}><strong>{Number(c.total_price_ex_vat).toLocaleString("sv-SE")} kr exkl. moms</strong><span>Faktura {c.fortnox_invoice_number??"skapas"}</span><small>Status: {c.status}</small></div>)}</div></aside></section></main>;
}