import type{Metadata}from"next";import Link from"next/link";import{notFound}from"next/navigation";import{ArrowRight,BadgeCheck,Globe,Mail,MapPin,Phone}from"lucide-react";import{createClient}from"@/lib/supabase/server";
type Props={params:Promise<{slug:string}>};
async function getCompany(slug:string){const supabase=await createClient();const{data}=await supabase.from("partner_organizations").select("id,name,slug,description,public_email,phone,website_url,address,postal_code,city,opening_hours,logo_path,profile_published").eq("slug",slug).eq("status","active").eq("profile_published",true).single();if(!data)return null;const{data:markets}=await supabase.from("partner_placements").select("municipalities(name,slug),service_categories(name,slug)").eq("organization_id",data.id).eq("status","active");const logo=data.logo_path?supabase.storage.from("partner-assets").getPublicUrl(data.logo_path).data.publicUrl:null;return{company:data,markets:markets??[],logo};}
export async function generateMetadata({params}:Props):Promise<Metadata>{const result=await getCompany((await params).slug);return result?{title:`${result.company.name} – BoLiv Partner`,description:result.company.description??`${result.company.name} är utvald BoLiv Partner.`}:{};}
export default async function CompanyPage({params}:Props){const result=await getCompany((await params).slug);if(!result)notFound();const{company,markets,logo}=result;
 return <main><section className="company-hero"><div className="container company-hero-grid"><div>{logo?<img className="company-logo" src={logo} alt={company.name}/>:null}<span className="partner-label">Utvald BoLiv Partner</span><h1>{company.name}</h1><p>{company.description??"Lokal partner för ditt nästa bostadsprojekt."}</p></div><BadgeCheck/></div></section>
 <section className="section container company-grid"><div><span className="kicker">Våra marknader</span><h2>Här hjälper vi BoLivs besökare.</h2><div className="company-markets">{markets.map((m:any)=><article key={`${m.service_categories?.slug}:${m.municipalities?.slug}`}><MapPin/><span><strong>{m.service_categories?.name}</strong><small>{m.municipalities?.name}</small></span></article>)}</div></div>
 <aside className="partner-admin-section"><h2>Kontakta företaget</h2>{company.phone&&<a href={`tel:${company.phone}`}><Phone/>{company.phone}</a>}{company.public_email&&<a href={`mailto:${company.public_email}`}><Mail/>{company.public_email}</a>}{company.website_url&&<a href={company.website_url} target="_blank" rel="sponsored noopener"><Globe/>Besök webbplatsen <ArrowRight/></a>}{company.address&&<p><MapPin/>{company.address}, {company.postal_code} {company.city}</p>}{company.opening_hours&&<p><strong>Öppettider</strong><br/>{company.opening_hours}</p>}</aside></section>
 <section className="partner-cta"><div className="container"><div><span className="kicker">BoLiv Partner</span><h2>Behöver ni också lokal synlighet?</h2></div><Link className="button" href="/partner/ansok">Se lediga marknader <ArrowRight/></Link></div></section></main>;
}