-- Sveriges samtliga 290 kommuner enligt SCB:s indelning 2026.
-- Källa: https://www.scb.se/hitta-statistik/regional-statistik-och-kartor/regionala-indelningar/lan-och-kommuner/lan-och-kommuner-i-kodnummerordning/

insert into public.municipalities (code, name, county_name, slug)
values
  ('0114', 'Upplands Väsby', 'Stockholms län', 'upplands-vasby'),
  ('0115', 'Vallentuna', 'Stockholms län', 'vallentuna'),
  ('0117', 'Österåker', 'Stockholms län', 'osteraker'),
  ('0120', 'Värmdö', 'Stockholms län', 'varmdo'),
  ('0123', 'Järfälla', 'Stockholms län', 'jarfalla'),
  ('0125', 'Ekerö', 'Stockholms län', 'ekero'),
  ('0126', 'Huddinge', 'Stockholms län', 'huddinge'),
  ('0127', 'Botkyrka', 'Stockholms län', 'botkyrka'),
  ('0128', 'Salem', 'Stockholms län', 'salem'),
  ('0136', 'Haninge', 'Stockholms län', 'haninge'),
  ('0138', 'Tyresö', 'Stockholms län', 'tyreso'),
  ('0139', 'Upplands-Bro', 'Stockholms län', 'upplands-bro'),
  ('0140', 'Nykvarn', 'Stockholms län', 'nykvarn'),
  ('0160', 'Täby', 'Stockholms län', 'taby'),
  ('0162', 'Danderyd', 'Stockholms län', 'danderyd'),
  ('0163', 'Sollentuna', 'Stockholms län', 'sollentuna'),
  ('0180', 'Stockholm', 'Stockholms län', 'stockholm'),
  ('0181', 'Södertälje', 'Stockholms län', 'sodertalje'),
  ('0182', 'Nacka', 'Stockholms län', 'nacka'),
  ('0183', 'Sundbyberg', 'Stockholms län', 'sundbyberg'),
  ('0184', 'Solna', 'Stockholms län', 'solna'),
  ('0186', 'Lidingö', 'Stockholms län', 'lidingo'),
  ('0187', 'Vaxholm', 'Stockholms län', 'vaxholm'),
  ('0188', 'Norrtälje', 'Stockholms län', 'norrtalje'),
  ('0191', 'Sigtuna', 'Stockholms län', 'sigtuna'),
  ('0192', 'Nynäshamn', 'Stockholms län', 'nynashamn'),
  ('0305', 'Håbo', 'Uppsala län', 'habo-uppsala'),
  ('0319', 'Älvkarleby', 'Uppsala län', 'alvkarleby'),
  ('0330', 'Knivsta', 'Uppsala län', 'knivsta'),
  ('0331', 'Heby', 'Uppsala län', 'heby'),
  ('0360', 'Tierp', 'Uppsala län', 'tierp'),
  ('0380', 'Uppsala', 'Uppsala län', 'uppsala'),
  ('0381', 'Enköping', 'Uppsala län', 'enkoping'),
  ('0382', 'Östhammar', 'Uppsala län', 'osthammar'),
  ('0428', 'Vingåker', 'Södermanlands län', 'vingaker'),
  ('0461', 'Gnesta', 'Södermanlands län', 'gnesta'),
  ('0480', 'Nyköping', 'Södermanlands län', 'nykoping'),
  ('0481', 'Oxelösund', 'Södermanlands län', 'oxelosund'),
  ('0482', 'Flen', 'Södermanlands län', 'flen'),
  ('0483', 'Katrineholm', 'Södermanlands län', 'katrineholm'),
  ('0484', 'Eskilstuna', 'Södermanlands län', 'eskilstuna'),
  ('0486', 'Strängnäs', 'Södermanlands län', 'strangnas'),
  ('0488', 'Trosa', 'Södermanlands län', 'trosa'),
  ('0509', 'Ödeshög', 'Östergötlands län', 'odeshog'),
  ('0512', 'Ydre', 'Östergötlands län', 'ydre'),
  ('0513', 'Kinda', 'Östergötlands län', 'kinda'),
  ('0560', 'Boxholm', 'Östergötlands län', 'boxholm'),
  ('0561', 'Åtvidaberg', 'Östergötlands län', 'atvidaberg'),
  ('0562', 'Finspång', 'Östergötlands län', 'finspang'),
  ('0563', 'Valdemarsvik', 'Östergötlands län', 'valdemarsvik'),
  ('0580', 'Linköping', 'Östergötlands län', 'linkoping'),
  ('0581', 'Norrköping', 'Östergötlands län', 'norrkoping'),
  ('0582', 'Söderköping', 'Östergötlands län', 'soderkoping'),
  ('0583', 'Motala', 'Östergötlands län', 'motala'),
  ('0584', 'Vadstena', 'Östergötlands län', 'vadstena'),
  ('0586', 'Mjölby', 'Östergötlands län', 'mjolby'),
  ('0604', 'Aneby', 'Jönköpings län', 'aneby'),
  ('0617', 'Gnosjö', 'Jönköpings län', 'gnosjo'),
  ('0642', 'Mullsjö', 'Jönköpings län', 'mullsjo'),
  ('0643', 'Habo', 'Jönköpings län', 'habo-jonkoping'),
  ('0662', 'Gislaved', 'Jönköpings län', 'gislaved'),
  ('0665', 'Vaggeryd', 'Jönköpings län', 'vaggeryd'),
  ('0680', 'Jönköping', 'Jönköpings län', 'jonkoping'),
  ('0682', 'Nässjö', 'Jönköpings län', 'nassjo'),
  ('0683', 'Värnamo', 'Jönköpings län', 'varnamo'),
  ('0684', 'Sävsjö', 'Jönköpings län', 'savsjo'),
  ('0685', 'Vetlanda', 'Jönköpings län', 'vetlanda'),
  ('0686', 'Eksjö', 'Jönköpings län', 'eksjo'),
  ('0687', 'Tranås', 'Jönköpings län', 'tranas'),
  ('0760', 'Uppvidinge', 'Kronobergs län', 'uppvidinge'),
  ('0761', 'Lessebo', 'Kronobergs län', 'lessebo'),
  ('0763', 'Tingsryd', 'Kronobergs län', 'tingsryd'),
  ('0764', 'Alvesta', 'Kronobergs län', 'alvesta'),
  ('0765', 'Älmhult', 'Kronobergs län', 'almhult'),
  ('0767', 'Markaryd', 'Kronobergs län', 'markaryd'),
  ('0780', 'Växjö', 'Kronobergs län', 'vaxjo'),
  ('0781', 'Ljungby', 'Kronobergs län', 'ljungby'),
  ('0821', 'Högsby', 'Kalmar län', 'hogsby'),
  ('0834', 'Torsås', 'Kalmar län', 'torsas'),
  ('0840', 'Mörbylånga', 'Kalmar län', 'morbylanga'),
  ('0860', 'Hultsfred', 'Kalmar län', 'hultsfred'),
  ('0861', 'Mönsterås', 'Kalmar län', 'monsteras'),
  ('0862', 'Emmaboda', 'Kalmar län', 'emmaboda'),
  ('0880', 'Kalmar', 'Kalmar län', 'kalmar'),
  ('0881', 'Nybro', 'Kalmar län', 'nybro'),
  ('0882', 'Oskarshamn', 'Kalmar län', 'oskarshamn'),
  ('0883', 'Västervik', 'Kalmar län', 'vastervik'),
  ('0884', 'Vimmerby', 'Kalmar län', 'vimmerby'),
  ('0885', 'Borgholm', 'Kalmar län', 'borgholm'),
  ('0980', 'Gotland', 'Gotlands län', 'gotland'),
  ('1060', 'Olofström', 'Blekinge län', 'olofstrom'),
  ('1080', 'Karlskrona', 'Blekinge län', 'karlskrona'),
  ('1081', 'Ronneby', 'Blekinge län', 'ronneby'),
  ('1082', 'Karlshamn', 'Blekinge län', 'karlshamn'),
  ('1083', 'Sölvesborg', 'Blekinge län', 'solvesborg'),
  ('1214', 'Svalöv', 'Skåne län', 'svalov'),
  ('1230', 'Staffanstorp', 'Skåne län', 'staffanstorp'),
  ('1231', 'Burlöv', 'Skåne län', 'burlov'),
  ('1233', 'Vellinge', 'Skåne län', 'vellinge'),
  ('1256', 'Östra Göinge', 'Skåne län', 'ostra-goinge'),
  ('1257', 'Örkelljunga', 'Skåne län', 'orkelljunga'),
  ('1260', 'Bjuv', 'Skåne län', 'bjuv'),
  ('1261', 'Kävlinge', 'Skåne län', 'kavlinge'),
  ('1262', 'Lomma', 'Skåne län', 'lomma'),
  ('1263', 'Svedala', 'Skåne län', 'svedala'),
  ('1264', 'Skurup', 'Skåne län', 'skurup'),
  ('1265', 'Sjöbo', 'Skåne län', 'sjobo'),
  ('1266', 'Hörby', 'Skåne län', 'horby'),
  ('1267', 'Höör', 'Skåne län', 'hoor'),
  ('1270', 'Tomelilla', 'Skåne län', 'tomelilla'),
  ('1272', 'Bromölla', 'Skåne län', 'bromolla'),
  ('1273', 'Osby', 'Skåne län', 'osby'),
  ('1275', 'Perstorp', 'Skåne län', 'perstorp'),
  ('1276', 'Klippan', 'Skåne län', 'klippan'),
  ('1277', 'Åstorp', 'Skåne län', 'astorp'),
  ('1278', 'Båstad', 'Skåne län', 'bastad'),
  ('1280', 'Malmö', 'Skåne län', 'malmo'),
  ('1281', 'Lund', 'Skåne län', 'lund'),
  ('1282', 'Landskrona', 'Skåne län', 'landskrona'),
  ('1283', 'Helsingborg', 'Skåne län', 'helsingborg'),
  ('1284', 'Höganäs', 'Skåne län', 'hoganas'),
  ('1285', 'Eslöv', 'Skåne län', 'eslov'),
  ('1286', 'Ystad', 'Skåne län', 'ystad'),
  ('1287', 'Trelleborg', 'Skåne län', 'trelleborg'),
  ('1290', 'Kristianstad', 'Skåne län', 'kristianstad'),
  ('1291', 'Simrishamn', 'Skåne län', 'simrishamn'),
  ('1292', 'Ängelholm', 'Skåne län', 'angelholm'),
  ('1293', 'Hässleholm', 'Skåne län', 'hassleholm'),
  ('1315', 'Hylte', 'Hallands län', 'hylte'),
  ('1380', 'Halmstad', 'Hallands län', 'halmstad'),
  ('1381', 'Laholm', 'Hallands län', 'laholm'),
  ('1382', 'Falkenberg', 'Hallands län', 'falkenberg'),
  ('1383', 'Varberg', 'Hallands län', 'varberg'),
  ('1384', 'Kungsbacka', 'Hallands län', 'kungsbacka'),
  ('1401', 'Härryda', 'Västra Götalands län', 'harryda'),
  ('1402', 'Partille', 'Västra Götalands län', 'partille'),
  ('1407', 'Öckerö', 'Västra Götalands län', 'ockero'),
  ('1415', 'Stenungsund', 'Västra Götalands län', 'stenungsund'),
  ('1419', 'Tjörn', 'Västra Götalands län', 'tjorn'),
  ('1421', 'Orust', 'Västra Götalands län', 'orust'),
  ('1427', 'Sotenäs', 'Västra Götalands län', 'sotenas'),
  ('1430', 'Munkedal', 'Västra Götalands län', 'munkedal'),
  ('1435', 'Tanum', 'Västra Götalands län', 'tanum'),
  ('1438', 'Dals-Ed', 'Västra Götalands län', 'dals-ed'),
  ('1439', 'Färgelanda', 'Västra Götalands län', 'fargelanda'),
  ('1440', 'Ale', 'Västra Götalands län', 'ale'),
  ('1441', 'Lerum', 'Västra Götalands län', 'lerum'),
  ('1442', 'Vårgårda', 'Västra Götalands län', 'vargarda'),
  ('1443', 'Bollebygd', 'Västra Götalands län', 'bollebygd'),
  ('1444', 'Grästorp', 'Västra Götalands län', 'grastorp'),
  ('1445', 'Essunga', 'Västra Götalands län', 'essunga'),
  ('1446', 'Karlsborg', 'Västra Götalands län', 'karlsborg'),
  ('1447', 'Gullspång', 'Västra Götalands län', 'gullspang'),
  ('1452', 'Tranemo', 'Västra Götalands län', 'tranemo'),
  ('1460', 'Bengtsfors', 'Västra Götalands län', 'bengtsfors'),
  ('1461', 'Mellerud', 'Västra Götalands län', 'mellerud'),
  ('1462', 'Lilla Edet', 'Västra Götalands län', 'lilla-edet'),
  ('1463', 'Mark', 'Västra Götalands län', 'mark'),
  ('1465', 'Svenljunga', 'Västra Götalands län', 'svenljunga'),
  ('1466', 'Herrljunga', 'Västra Götalands län', 'herrljunga'),
  ('1470', 'Vara', 'Västra Götalands län', 'vara'),
  ('1471', 'Götene', 'Västra Götalands län', 'gotene'),
  ('1472', 'Tibro', 'Västra Götalands län', 'tibro'),
  ('1473', 'Töreboda', 'Västra Götalands län', 'toreboda'),
  ('1480', 'Göteborg', 'Västra Götalands län', 'goteborg'),
  ('1481', 'Mölndal', 'Västra Götalands län', 'molndal'),
  ('1482', 'Kungälv', 'Västra Götalands län', 'kungalv'),
  ('1484', 'Lysekil', 'Västra Götalands län', 'lysekil'),
  ('1485', 'Uddevalla', 'Västra Götalands län', 'uddevalla'),
  ('1486', 'Strömstad', 'Västra Götalands län', 'stromstad'),
  ('1487', 'Vänersborg', 'Västra Götalands län', 'vanersborg'),
  ('1488', 'Trollhättan', 'Västra Götalands län', 'trollhattan'),
  ('1489', 'Alingsås', 'Västra Götalands län', 'alingsas'),
  ('1490', 'Borås', 'Västra Götalands län', 'boras'),
  ('1491', 'Ulricehamn', 'Västra Götalands län', 'ulricehamn'),
  ('1492', 'Åmål', 'Västra Götalands län', 'amal'),
  ('1493', 'Mariestad', 'Västra Götalands län', 'mariestad'),
  ('1494', 'Lidköping', 'Västra Götalands län', 'lidkoping'),
  ('1495', 'Skara', 'Västra Götalands län', 'skara'),
  ('1496', 'Skövde', 'Västra Götalands län', 'skovde'),
  ('1497', 'Hjo', 'Västra Götalands län', 'hjo'),
  ('1498', 'Tidaholm', 'Västra Götalands län', 'tidaholm'),
  ('1499', 'Falköping', 'Västra Götalands län', 'falkoping'),
  ('1715', 'Kil', 'Värmlands län', 'kil'),
  ('1730', 'Eda', 'Värmlands län', 'eda'),
  ('1737', 'Torsby', 'Värmlands län', 'torsby'),
  ('1760', 'Storfors', 'Värmlands län', 'storfors'),
  ('1761', 'Hammarö', 'Värmlands län', 'hammaro'),
  ('1762', 'Munkfors', 'Värmlands län', 'munkfors'),
  ('1763', 'Forshaga', 'Värmlands län', 'forshaga'),
  ('1764', 'Grums', 'Värmlands län', 'grums'),
  ('1765', 'Årjäng', 'Värmlands län', 'arjang'),
  ('1766', 'Sunne', 'Värmlands län', 'sunne'),
  ('1780', 'Karlstad', 'Värmlands län', 'karlstad'),
  ('1781', 'Kristinehamn', 'Värmlands län', 'kristinehamn'),
  ('1782', 'Filipstad', 'Värmlands län', 'filipstad'),
  ('1783', 'Hagfors', 'Värmlands län', 'hagfors'),
  ('1784', 'Arvika', 'Värmlands län', 'arvika'),
  ('1785', 'Säffle', 'Värmlands län', 'saffle'),
  ('1814', 'Lekeberg', 'Örebro län', 'lekeberg'),
  ('1860', 'Laxå', 'Örebro län', 'laxa'),
  ('1861', 'Hallsberg', 'Örebro län', 'hallsberg'),
  ('1862', 'Degerfors', 'Örebro län', 'degerfors'),
  ('1863', 'Hällefors', 'Örebro län', 'hallefors'),
  ('1864', 'Ljusnarsberg', 'Örebro län', 'ljusnarsberg'),
  ('1880', 'Örebro', 'Örebro län', 'orebro'),
  ('1881', 'Kumla', 'Örebro län', 'kumla'),
  ('1882', 'Askersund', 'Örebro län', 'askersund'),
  ('1883', 'Karlskoga', 'Örebro län', 'karlskoga'),
  ('1884', 'Nora', 'Örebro län', 'nora'),
  ('1885', 'Lindesberg', 'Örebro län', 'lindesberg'),
  ('1904', 'Skinnskatteberg', 'Västmanlands län', 'skinnskatteberg'),
  ('1907', 'Surahammar', 'Västmanlands län', 'surahammar'),
  ('1960', 'Kungsör', 'Västmanlands län', 'kungsor'),
  ('1961', 'Hallstahammar', 'Västmanlands län', 'hallstahammar'),
  ('1962', 'Norberg', 'Västmanlands län', 'norberg'),
  ('1980', 'Västerås', 'Västmanlands län', 'vasteras'),
  ('1981', 'Sala', 'Västmanlands län', 'sala'),
  ('1982', 'Fagersta', 'Västmanlands län', 'fagersta'),
  ('1983', 'Köping', 'Västmanlands län', 'koping'),
  ('1984', 'Arboga', 'Västmanlands län', 'arboga'),
  ('2021', 'Vansbro', 'Dalarnas län', 'vansbro'),
  ('2023', 'Malung-Sälen', 'Dalarnas län', 'malung-salen'),
  ('2026', 'Gagnef', 'Dalarnas län', 'gagnef'),
  ('2029', 'Leksand', 'Dalarnas län', 'leksand'),
  ('2031', 'Rättvik', 'Dalarnas län', 'rattvik'),
  ('2034', 'Orsa', 'Dalarnas län', 'orsa'),
  ('2039', 'Älvdalen', 'Dalarnas län', 'alvdalen'),
  ('2061', 'Smedjebacken', 'Dalarnas län', 'smedjebacken'),
  ('2062', 'Mora', 'Dalarnas län', 'mora'),
  ('2080', 'Falun', 'Dalarnas län', 'falun'),
  ('2081', 'Borlänge', 'Dalarnas län', 'borlange'),
  ('2082', 'Säter', 'Dalarnas län', 'sater'),
  ('2083', 'Hedemora', 'Dalarnas län', 'hedemora'),
  ('2084', 'Avesta', 'Dalarnas län', 'avesta'),
  ('2085', 'Ludvika', 'Dalarnas län', 'ludvika'),
  ('2101', 'Ockelbo', 'Gävleborgs län', 'ockelbo'),
  ('2104', 'Hofors', 'Gävleborgs län', 'hofors'),
  ('2121', 'Ovanåker', 'Gävleborgs län', 'ovanaker'),
  ('2132', 'Nordanstig', 'Gävleborgs län', 'nordanstig'),
  ('2161', 'Ljusdal', 'Gävleborgs län', 'ljusdal'),
  ('2180', 'Gävle', 'Gävleborgs län', 'gavle'),
  ('2181', 'Sandviken', 'Gävleborgs län', 'sandviken'),
  ('2182', 'Söderhamn', 'Gävleborgs län', 'soderhamn'),
  ('2183', 'Bollnäs', 'Gävleborgs län', 'bollnas'),
  ('2184', 'Hudiksvall', 'Gävleborgs län', 'hudiksvall'),
  ('2260', 'Ånge', 'Västernorrlands län', 'ange'),
  ('2262', 'Timrå', 'Västernorrlands län', 'timra'),
  ('2280', 'Härnösand', 'Västernorrlands län', 'harnosand'),
  ('2281', 'Sundsvall', 'Västernorrlands län', 'sundsvall'),
  ('2282', 'Kramfors', 'Västernorrlands län', 'kramfors'),
  ('2283', 'Sollefteå', 'Västernorrlands län', 'solleftea'),
  ('2284', 'Örnsköldsvik', 'Västernorrlands län', 'ornskoldsvik'),
  ('2303', 'Ragunda', 'Jämtlands län', 'ragunda'),
  ('2305', 'Bräcke', 'Jämtlands län', 'bracke'),
  ('2309', 'Krokom', 'Jämtlands län', 'krokom'),
  ('2313', 'Strömsund', 'Jämtlands län', 'stromsund'),
  ('2321', 'Åre', 'Jämtlands län', 'are'),
  ('2326', 'Berg', 'Jämtlands län', 'berg'),
  ('2361', 'Härjedalen', 'Jämtlands län', 'harjedalen'),
  ('2380', 'Östersund', 'Jämtlands län', 'ostersund'),
  ('2401', 'Nordmaling', 'Västerbottens län', 'nordmaling'),
  ('2403', 'Bjurholm', 'Västerbottens län', 'bjurholm'),
  ('2404', 'Vindeln', 'Västerbottens län', 'vindeln'),
  ('2409', 'Robertsfors', 'Västerbottens län', 'robertsfors'),
  ('2417', 'Norsjö', 'Västerbottens län', 'norsjo'),
  ('2418', 'Malå', 'Västerbottens län', 'mala'),
  ('2421', 'Storuman', 'Västerbottens län', 'storuman'),
  ('2422', 'Sorsele', 'Västerbottens län', 'sorsele'),
  ('2425', 'Dorotea', 'Västerbottens län', 'dorotea'),
  ('2460', 'Vännäs', 'Västerbottens län', 'vannas'),
  ('2462', 'Vilhelmina', 'Västerbottens län', 'vilhelmina'),
  ('2463', 'Åsele', 'Västerbottens län', 'asele'),
  ('2480', 'Umeå', 'Västerbottens län', 'umea'),
  ('2481', 'Lycksele', 'Västerbottens län', 'lycksele'),
  ('2482', 'Skellefteå', 'Västerbottens län', 'skelleftea'),
  ('2505', 'Arvidsjaur', 'Norrbottens län', 'arvidsjaur'),
  ('2506', 'Arjeplog', 'Norrbottens län', 'arjeplog'),
  ('2510', 'Jokkmokk', 'Norrbottens län', 'jokkmokk'),
  ('2513', 'Överkalix', 'Norrbottens län', 'overkalix'),
  ('2514', 'Kalix', 'Norrbottens län', 'kalix'),
  ('2518', 'Övertorneå', 'Norrbottens län', 'overtornea'),
  ('2521', 'Pajala', 'Norrbottens län', 'pajala'),
  ('2523', 'Gällivare', 'Norrbottens län', 'gallivare'),
  ('2560', 'Älvsbyn', 'Norrbottens län', 'alvsbyn'),
  ('2580', 'Luleå', 'Norrbottens län', 'lulea'),
  ('2581', 'Piteå', 'Norrbottens län', 'pitea'),
  ('2582', 'Boden', 'Norrbottens län', 'boden'),
  ('2583', 'Haparanda', 'Norrbottens län', 'haparanda'),
  ('2584', 'Kiruna', 'Norrbottens län', 'kiruna');
on conflict (code) do update set
  name = excluded.name,
  county_name = excluded.county_name,
  slug = excluded.slug;

do $$
begin
  if (select count(*) from public.municipalities) <> 290 then
    raise exception 'Förväntade 290 kommuner men hittade %', (select count(*) from public.municipalities);
  end if;
end $$;
