-- BoLiv Partner: complete initial catalogue of sellable service categories.

insert into public.service_categories (name, slug, description)
values
  ('Arkitekt', 'arkitekt', 'Arkitektur, ombyggnad, tillbyggnad och bygglovsunderlag.'),
  ('Besiktningsföretag', 'besiktningsforetag', 'Överlåtelsebesiktning, statusbesiktning och teknisk rådgivning.'),
  ('Bredband och fiber', 'bredband-fiber', 'Fiberanslutning, nätverk, wifi och bredbandslösningar.'),
  ('Byggföretag', 'byggforetag', 'Nybyggnad, tillbyggnad, ombyggnad och totalentreprenad.'),
  ('Bygglovskonsult', 'bygglovskonsult', 'Bygglov, anmälan, ritningar och kontakt med kommunen.'),
  ('Elektriker', 'elektriker', 'Elinstallation, felsökning, laddbox och elsäkerhet.'),
  ('Energikonsult', 'energikonsult', 'Energideklaration, energikartläggning och effektivisering.'),
  ('Fastighetsmäklare', 'fastighetsmaklare', 'Värdering, försäljning och köp av bostad.'),
  ('Flyttfirma', 'flyttfirma', 'Bohagsflytt, packning, magasinering och flyttservice.'),
  ('Fukttekniker', 'fukttekniker', 'Fuktmätning, skadeutredning och åtgärdsförslag.'),
  ('Fönster och dörrar', 'fonster-dorrar', 'Fönsterbyte, dörrbyte, renovering och energieffektivisering.'),
  ('Försäkring', 'forsakring', 'Villa-, hem-, bostadsrätts- och fritidshusförsäkring.'),
  ('Golvläggare', 'golvlaggare', 'Trägolv, parkett, laminat, plastmatta och golvrenovering.'),
  ('Grund och dränering', 'grund-dranering', 'Dränering, grundisolering, fuktskydd och grundarbeten.'),
  ('Hemstädning', 'hemstadning', 'Hemstädning, storstädning och återkommande städtjänster.'),
  ('Homestyling', 'homestyling', 'Styling, inredning och förberedelse inför bostadsförsäljning.'),
  ('Inredningsarkitekt', 'inredningsarkitekt', 'Inredningskoncept, planlösning, färg och materialval.'),
  ('Isoleringsföretag', 'isolering', 'Tilläggsisolering av vind, vägg, grund och klimatskal.'),
  ('Jurist - fastighet', 'fastighetsjurist', 'Avtal, fel i fastighet, servitut och bostadsjuridik.'),
  ('Kakel och klinker', 'kakel-klinker', 'Plattsättning i badrum, kök och andra våtutrymmen.'),
  ('Kamin och eldstad', 'kamin-eldstad', 'Installation, renovering och service av kamin och eldstad.'),
  ('Köksföretag', 'koksforetag', 'Köksplanering, köksrenovering och montering.'),
  ('Larm och säkerhet', 'larm-sakerhet', 'Inbrottslarm, kameror, passersystem och smart säkerhet.'),
  ('Låssmed', 'lassmed', 'Låsbyte, låssystem, dörrsäkerhet och akut låsservice.'),
  ('Mark och schakt', 'mark-schakt', 'Schaktning, planering, grundarbete och markentreprenad.'),
  ('Murare', 'murare', 'Murning, puts, skorsten, fasad och eldstadsarbeten.'),
  ('Målare', 'malare', 'Invändig och utvändig målning, tapetsering och fasadbehandling.'),
  ('Pool och spa', 'pool-spa', 'Poolbygge, spabad, rening, service och vinterstängning.'),
  ('Sanering och skadeservice', 'sanering-skadeservice', 'Vatten-, brand-, lukt-, mögel- och miljösanering.'),
  ('Skadedjursbekämpning', 'skadedjursbekampning', 'Förebyggande skydd och bekämpning av skadedjur.'),
  ('Skorsten och sotning', 'skorsten-sotning', 'Sotning, brandskyddskontroll och skorstensrenovering.'),
  ('Solceller', 'solceller', 'Solcellsanläggning, batterilagring och energioptimering.'),
  ('Takläggare', 'taklaggare', 'Takbyte, takrenovering, reparation och taksäkerhet.'),
  ('Trädgård och anläggning', 'tradgard-anlaggning', 'Trädgårdsdesign, stenläggning, murar och utemiljö.'),
  ('Trädfällning och arborist', 'tradfallning-arborist', 'Trädfällning, beskärning, riskbedömning och stubbfräsning.'),
  ('TV och hemelektronik', 'tv-hemelektronik', 'TV, ljud, antenn, parabol och installation i hemmet.'),
  ('Ventilation', 'ventilation', 'Ventilationsservice, OVK, kanalrengöring och inneklimat.'),
  ('Vatten och brunn', 'vatten-brunn', 'Vattenprov, vattenrening, brunnsborrning och pumpar.'),
  ('Värmepumpar', 'varmepumpar', 'Installation och service av berg-, luft- och frånluftsvärmepumpar.'),
  ('VVS och rörmokare', 'vvs-rormokare', 'Rörarbete, värme, vatten, avlopp och VVS-service.'),
  ('Våtrum och badrum', 'vatrum-badrum', 'Badrumsrenovering, tätskikt och våtrumsentreprenad.'),
  ('Återvinning och bortforsling', 'atervinning-bortforsling', 'Bortforsling, röjning, avfall och återvinning.')
on conflict (slug) do update set
  name = excluded.name,
  description = excluded.description;

